name: APK

on:
  push:
     branches: main
  pull_request:
     branches: main

jobs:
  p4a:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: pip install python-for-android
      - run: python ./main.py apk --package "org.tyler887.droidterm"
      - uses: actions/upload-artifact@v2
        with:
          name: dt
          path: ./dt.apk
